/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "fw_update.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(gridware_FirmwareImagePage, gridware_FirmwareImagePage, 2)


PB_BIND(gridware_DeviceResponse, gridware_DeviceResponse, AUTO)



