/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_GRIDWARE_FW_UPDATE_PB_H_INCLUDED
#define PB_GRIDWARE_FW_UPDATE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* The device sends back a response for each message, describing whether
 or not the received CRC was correct. */
typedef struct _gridware_DeviceResponse { 
    /* Whether or not the image was received and the CRC verified */
    bool verified; 
} gridware_DeviceResponse;

typedef PB_BYTES_ARRAY_T(2048) gridware_FirmwareImagePage_page_t;
typedef PB_BYTES_ARRAY_T(2) gridware_FirmwareImagePage_crc_t;
/* The server sends multiple chunks of a new firmware binary to the device
 who programs its own flash memory with the new application image. */
typedef struct _gridware_FirmwareImagePage { 
    /* One page of the new firmware image. */
    gridware_FirmwareImagePage_page_t page; 
    /* CRC of the data to check for integrity */
    gridware_FirmwareImagePage_crc_t crc; 
    /* Whether or not this is the last page to come. */
    bool last; 
} gridware_FirmwareImagePage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define gridware_FirmwareImagePage_init_default  {{0, {0}}, {0, {0}}, 0}
#define gridware_DeviceResponse_init_default     {0}
#define gridware_FirmwareImagePage_init_zero     {{0, {0}}, {0, {0}}, 0}
#define gridware_DeviceResponse_init_zero        {0}

/* Field tags (for use in manual encoding/decoding) */
#define gridware_DeviceResponse_verified_tag     1
#define gridware_FirmwareImagePage_page_tag      1
#define gridware_FirmwareImagePage_crc_tag       2
#define gridware_FirmwareImagePage_last_tag      3

/* Struct field encoding specification for nanopb */
#define gridware_FirmwareImagePage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    page,              1) \
X(a, STATIC,   SINGULAR, BYTES,    crc,               2) \
X(a, STATIC,   SINGULAR, BOOL,     last,              3)
#define gridware_FirmwareImagePage_CALLBACK NULL
#define gridware_FirmwareImagePage_DEFAULT NULL

#define gridware_DeviceResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     verified,          1)
#define gridware_DeviceResponse_CALLBACK NULL
#define gridware_DeviceResponse_DEFAULT NULL

extern const pb_msgdesc_t gridware_FirmwareImagePage_msg;
extern const pb_msgdesc_t gridware_DeviceResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define gridware_FirmwareImagePage_fields &gridware_FirmwareImagePage_msg
#define gridware_DeviceResponse_fields &gridware_DeviceResponse_msg

/* Maximum encoded size of messages (where known) */
#define gridware_DeviceResponse_size             2
#define gridware_FirmwareImagePage_size          2057

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
